"""
Beyond Python: what Justify can say about every other file in a repository.

Dead code needs a language's own scoping and import rules to be found safely, and Justify
claims it only where it has them — Python. Two things hold for any language, though:

* a census — what the repository is made of, language by language, file by file;
* copies — the same block of code living in two places. Found the way PMD's copy-paste
  detector finds it: runs of lines that match once whitespace, comments, imports and lone
  brackets are set aside. A copy is reported once, at the later place, pointing at the first.

Nothing here guesses. A block is a copy because the same lines are in two files.
"""

from __future__ import annotations

import pathlib
import re
from collections import defaultdict
from dataclasses import dataclass, field

from .ingest import BINARY_SUFFIXES, inside, is_skipped
from .model import SIMPLIFY, Finding

LANGS: dict[str, str] = {
    ".py": "Python", ".pyi": "Python",
    ".js": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript", ".jsx": "JavaScript",
    ".ts": "TypeScript", ".tsx": "TypeScript", ".mts": "TypeScript", ".cts": "TypeScript",
    ".go": "Go", ".rs": "Rust", ".java": "Java", ".kt": "Kotlin", ".kts": "Kotlin", ".scala": "Scala",
    ".c": "C", ".h": "C/C++ header", ".cc": "C++", ".cpp": "C++", ".cxx": "C++", ".hpp": "C++", ".hh": "C++",
    ".cs": "C#", ".rb": "Ruby", ".php": "PHP", ".swift": "Swift", ".m": "Objective-C", ".mm": "Objective-C",
    ".dart": "Dart", ".lua": "Lua", ".r": "R", ".jl": "Julia", ".ex": "Elixir", ".exs": "Elixir",
    ".erl": "Erlang", ".hs": "Haskell", ".clj": "Clojure", ".sol": "Solidity", ".zig": "Zig", ".nim": "Nim",
    ".vue": "Vue", ".svelte": "Svelte", ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell", ".ps1": "PowerShell",
    ".sql": "SQL", ".html": "HTML", ".htm": "HTML", ".css": "CSS", ".scss": "SCSS", ".sass": "Sass",
    ".less": "Less", ".ipynb": "Jupyter notebook", ".md": "Markdown", ".mdx": "Markdown", ".rst": "reStructuredText",
    ".yml": "YAML", ".yaml": "YAML", ".json": "JSON", ".toml": "TOML", ".tf": "Terraform", ".xml": "XML",
    ".gradle": "Gradle", ".cmake": "CMake",
}
NAMED = {"Dockerfile": "Dockerfile", "Makefile": "Makefile", "CMakeLists.txt": "CMake", "Jenkinsfile": "Groovy"}

# languages whose copies are worth reporting — programming languages, not prose, data or styling
COPY_LANGS = {"JavaScript", "TypeScript", "Go", "Rust", "Java", "Kotlin", "Scala", "C", "C/C++ header", "C++",
              "C#", "Ruby", "PHP", "Swift", "Objective-C", "Dart", "Lua", "R", "Julia", "Elixir", "Erlang",
              "Haskell", "Clojure", "Solidity", "Zig", "Nim", "Vue", "Svelte", "Shell", "PowerShell"}
PROSE = {"Markdown", "reStructuredText"}
DATA = {"YAML", "JSON", "TOML", "XML"}

# folders that hold someone else's code or a build's output, in any language
EXTRA_SKIP = {"vendor", "third_party", "third-party", "bower_components", ".next", ".nuxt", ".svelte-kit",
              "target", "out", "coverage", ".gradle", "Pods", "DerivedData", ".turbo", ".cache", ".parcel-cache"}
GENERATED = re.compile(rb"(code generated|do not edit|@generated|auto-?generated|autogenerated)", re.I)

WINDOW = 6            # a copy is at least this many significant lines in a row
WINDOW_CHARS = 120    # ...holding at least this much text, so a run of `}` and `break;` is never one
MAX_FILE_BYTES = 512_000
MAX_COPY_LINES = 1_500_000

_C_LIKE = ("//",)
_HASH = ("#",)
_COMMENT_PREFIX = {
    **{lang: _C_LIKE for lang in ("JavaScript", "TypeScript", "Go", "Rust", "Java", "Kotlin", "Scala", "C",
                                  "C/C++ header", "C++", "C#", "Swift", "Objective-C", "Dart", "Solidity", "Zig",
                                  "Vue", "Svelte")},
    "PHP": ("//", "#"), "Ruby": _HASH, "Shell": _HASH, "R": _HASH, "Julia": _HASH, "Elixir": _HASH,
    "PowerShell": _HASH, "Nim": _HASH, "Lua": ("--",), "Haskell": ("--",), "Erlang": ("%",), "Clojure": (";",),
}
_BLOCK = {lang for lang, p in _COMMENT_PREFIX.items() if p is _C_LIKE or lang == "PHP"}
_IMPORTISH = re.compile(r"^(import\b|from\s+\S+\s+import\b|#\s*include\b|#\s*import\b|using\s+[\w.]+\s*;|"
                        r"require(_once)?\s*\(|package\s+[\w.]+|use\s+[\w:\\]+|extern\s+crate\b|@import\b|"
                        r"export\s+(\*|\{[^}]*\})\s+from\b|const\s+\w+\s*=\s*require\()")
_PUNCT_ONLY = re.compile(r"^[\s{}()\[\];,:.<>/*\\-]*$")


def language_of(rel: str) -> str | None:
    p = pathlib.PurePosixPath(rel)
    return NAMED.get(p.name) or LANGS.get(p.suffix.lower())


@dataclass
class CodeFile:
    rel: str
    lang: str
    lines: int
    text: str = field(repr=False, default="")
    generated: bool = False


def _skip(rel_parts: tuple[str, ...]) -> bool:
    return is_skipped(rel_parts) or any(part in EXTRA_SKIP for part in rel_parts[:-1])


def census(root: pathlib.Path) -> list[CodeFile]:
    """Every text file Justify recognises, with its language and line count. Python files are
    listed too, so the census is the whole repository; their audit happens elsewhere."""
    out: list[CodeFile] = []
    for path in sorted(root.rglob("*")):
        try:
            rel_parts = path.relative_to(root).parts
        except ValueError:
            continue
        if _skip(rel_parts) or path.suffix.lower() in BINARY_SUFFIXES:
            continue
        rel = "/".join(rel_parts)
        lang = language_of(rel)
        if not lang:
            continue
        try:
            if not inside(root, path) or path.stat().st_size > MAX_FILE_BYTES:
                continue
            raw = path.read_bytes()
        except OSError:
            continue
        if b"\0" in raw[:4096]:
            continue
        text = raw.decode("utf-8", errors="replace")
        lines = text.count("\n") + (0 if text.endswith("\n") or not text else 1)
        minified = lines and len(raw) / max(lines, 1) > 400
        out.append(CodeFile(rel=rel, lang=lang, lines=lines, text=text if lang in COPY_LANGS else "",
                            generated=bool(GENERATED.search(raw[:600])) or bool(minified)
                            or rel.endswith((".min.js", ".min.css", ".pb.go", ".g.dart", ".designer.cs"))))
    return out


def summary(files: list[CodeFile]) -> list[dict]:
    """Languages by size, each with how deeply Justify audits it."""
    by: dict[str, dict] = {}
    for f in files:
        row = by.setdefault(f.lang, {"name": f.lang, "files": 0, "lines": 0})
        row["files"] += 1
        row["lines"] += f.lines
    from . import langs
    full = langs.full_languages()
    for row in by.values():
        row["audit"] = ("full" if row["name"] == "Python" or row["name"] in full else
                        "copies" if row["name"] in COPY_LANGS else
                        "prose" if row["name"] in PROSE else "data" if row["name"] in DATA else "none")
    return sorted(by.values(), key=lambda r: (-r["lines"], r["name"]))


def _significant(f: CodeFile) -> list[tuple[int, str]]:
    """(line number, normalised text) for every line that carries code."""
    prefixes = _COMMENT_PREFIX.get(f.lang, ())
    block = f.lang in _BLOCK
    out: list[tuple[int, str]] = []
    in_block = False
    for i, raw in enumerate(f.text.split("\n"), start=1):
        s = raw.strip()
        if block:
            if in_block:
                end = s.find("*/")
                if end < 0:
                    continue
                s, in_block = s[end + 2:].strip(), False
            while "/*" in s:
                a = s.find("/*")
                b = s.find("*/", a + 2)
                if b < 0:
                    s, in_block = s[:a].strip(), True
                    break
                s = (s[:a] + " " + s[b + 2:]).strip()
        if not s or any(s.startswith(p) for p in prefixes) or s.startswith(("<!--", "*")):
            continue
        if _PUNCT_ONLY.match(s) or _IMPORTISH.match(s):
            continue
        out.append((i, " ".join(s.split())))
    return out


def copies(files: list[CodeFile]) -> tuple[list[Finding], dict]:
    """Blocks of code that already exist elsewhere in the repository."""
    todo = [f for f in files if f.lang in COPY_LANGS and not f.generated and f.text]
    sig: list[list[tuple[int, str]]] = []
    total = 0
    for f in todo:
        s = _significant(f)
        total += len(s)
        sig.append(s)
    note = {"files": len(todo), "lines": sum(f.lines for f in todo), "skipped": None}
    if total > MAX_COPY_LINES:
        note["skipped"] = f"{total:,} significant lines is more than the hosted limit for copy detection"
        return [], note

    first: dict[int, tuple[int, int]] = {}            # window hash -> (file index, position) seen first
    source: dict[tuple[int, int], tuple[int, int]] = {}    # (file, position) of a copy -> its original
    for fi, s in enumerate(sig):
        hashes = [hash(t) for _, t in s]
        for pos in range(0, len(s) - WINDOW + 1):
            if sum(len(s[pos + k][1]) for k in range(WINDOW)) < WINDOW_CHARS:
                continue
            key = hash(tuple(hashes[pos:pos + WINDOW]))
            seen = first.get(key)
            if seen is None:
                first[key] = (fi, pos)
            elif not (seen[0] == fi and pos - seen[1] < WINDOW):      # never a copy of itself
                source[(fi, pos)] = seen

    by_file: dict[int, list[int]] = defaultdict(list)
    for (f_i, pos) in source:
        by_file[f_i].append(pos)
    out: list[Finding] = []
    for fi, s in enumerate(sig):
        starts = sorted(by_file.get(fi, ()))
        if not starts:
            continue
        runs: list[tuple[int, int]] = []                  # (first window, last window) of each run
        for pos in starts:
            if runs and pos <= runs[-1][1] + WINDOW:
                runs[-1] = (runs[-1][0], pos)
            else:
                runs.append((pos, pos))
        f = todo[fi]
        for a, b in runs:
            start_line, end_line = s[a][0], s[min(b + WINDOW - 1, len(s) - 1)][0]
            of, opos = source[(fi, a)]
            orig = todo[of]
            n = end_line - start_line + 1
            out.append(Finding(kind="duplicate", file=f.rel, line=start_line, end_line=end_line,
                               name=f"{n}-line block", verdict=SIMPLIFY, lines=n,
                               evidence=[f"{orig.rel}:{sig[of][opos][0]}"],
                               reason=f"the same {f.lang} code is already at {orig.rel}:{sig[of][opos][0]} — "
                                      "keep one copy and call it from both places",
                               proof="not provable", final=SIMPLIFY))
    return out, note
